---
title: "Prep mark recapture for josh"
author: "Erin Cain"
date: '2022-05-19'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
```

## Load in data 

```{r}

standard_releases <- read_csv("../../data/standard-format-data/standard_release.csv")
standard_recapture <- read_csv("../../data/standard-format-data/standard_recapture.csv")

summarized_mark_recapture <- standard_releases %>% 
  left_join(standard_recapture, by = c("release_id" = "release_id", "stream" = "stream")) %>% 
  mutate(days_btw_release_and_catch = as_date(recaptured_date) - as_date(release_date), 
          caught_week_1 = ifelse(days_btw_release_and_catch >= 0 & days_btw_release_and_catch <= 7, number_recaptured, 0),
          caught_week_2 = ifelse(days_btw_release_and_catch > 7 & days_btw_release_and_catch <= 14, number_recaptured, 0),
          caught_week_3 = ifelse(days_btw_release_and_catch > 14 & days_btw_release_and_catch <= 21, number_recaptured, 0)) %>%
  group_by(stream, site,  release_id, release_date, number_released) %>% 
  summarize(total_fish_recaptured = sum(number_recaptured, na.rm = T), 
            caught_week_1 = sum(caught_week_1, na.rm = T),
            caught_week_2 = sum(caught_week_2, na.rm = T), 
            caught_week_3 = sum(caught_week_3, na.rm = T),
            median_fork_length_released = median(median_fork_length_released, na.rm = T),
            median_fork_length_recaptured = median(median_fork_length_recaptured, na.rm = T),
            flow_at_release = mean(flow_at_release, na.rm = T),
            temperature_at_release = mean(temperature_at_release, na.rm = T),
            turbidity_at_release = mean(turbidity_at_release, na.rm = T),
            efficiency = (total_fish_recaptured + 1)/(number_released + 1)) %>% glimpse

unique(summarized_mark_recapture$site)
glimpse(summarized_mark_recapture
        )

weekly_releases_and_recaptures <- summarized_mark_recapture %>% 
  mutate(year = year(release_date), 
         julian_week = week(release_date)) %>%
  select(-release_date) %>%
  rename(yr = year, Jwk = julian_week, 
         r1 = number_released, m1 = caught_week_1, 
         m2 = caught_week_2, m3 = caught_week_3) %>% 
  group_by(stream, yr, Jwk) %>%
  summarize(r1 = sum(r1, na.rm = T),
            m1 = sum(m1, na.rm = T), 
            m2 = sum(m2, na.rm = T),
            m3 = sum(m3, na.rm = T),
            released_fl = mean(median_fork_length_released, na.rm = T),
            recaptured_fl = mean(median_fork_length_recaptured, na.rm = T)) %>%
  mutate(m2 = ifelse(stream %in% c("battle creek", "clear creek"), NA, m2), # Replace 0 that were created in summarize statement with NA
         m3 = ifelse(stream %in% c("battle creek", "clear creek"), NA, m3)) 

unique(weekly_releases_and_recaptures$recaptured_fl)
unique(weekly_releases_and_recaptures$released_fl)
# Rename and reformat for Josh
# Do not summarize by week 
releases_and_recaptures <- summarized_mark_recapture %>% 
  select(-release_date) %>%
  rename(yr = year, Jwk = julian_week, 
         r1 = number_released, m1 = caught_week_1, 
         m2 = caught_week_2, m3 = caught_week_3) %>% 
  glimpse


# weekly summary csv
write_csv(weekly_releases_and_recaptures, "../../data/jpe-model-data/jpe_weekly_releases_and_recaptures.csv")

# row for each efficiency trial 
write_csv(releases_and_recaptures, "data/datasets_for_josh/jpe_releases_and_recaptures.csv")


f <- function(input, output) write_csv(input, file = output)

gcs_upload(weekly_releases_and_recaptures,
           object_function = f,
           type = "csv",
           name = "jpe-model-data/weekly_releases_and_recaptures.csv")
```

