---
title: "Knights Landing Catch Data Pull"
output: html_document
date: "2022-07-27"
---

This document queries the CAMP database provided by Nick Bauer (4/8/2022) to extract
RST catch data for Knights Landing trap. Previous files QC'd Excel files provided by
Jeanine Phillips.

*Important to filter releaseID == 0 or releasedID == 255 to exclude recaptures*

```{r}
library(tidyverse)
library(knitr)
library(Hmisc)
library(lubridate)
library(googleCloudStorageR)

gcs_auth(json_file = Sys.getenv("GCS_AUTH_FILE"))
gcs_global_bucket(bucket = Sys.getenv("GCS_DEFAULT_BUCKET"))
```

```{r}
# TODO
# Set up non-local connection with CAMP access database 
knights_access_db <- "/Users/ashleyvizek/code/CAMP_Knights.mdb"
mdb.get(knights_access_db, tables = T)

catch_raw <- mdb.get(knights_access_db, tables = "CatchRaw")
trap_visit <- mdb.get(knights_access_db, tables = "TrapVisit")
```

```{r}
# pull lookup tables
visit_type_lu <- mdb.get(knights_access_db, "luVisitType") %>% 
  select(-activeID) %>%glimpse

run_lu <- mdb.get(knights_access_db, "luRun") %>% 
  select(-activeID) %>% glimpse

run_method_lu <- mdb.get(knights_access_db, "luRunMethod") %>% 
  select(-activeID) %>% glimpse

lifestage_lu <- mdb.get(knights_access_db, "luLifeStage") %>% 
  select(-activeID) %>% glimpse

taxon_lu <-  mdb.get(knights_access_db, "luTaxon") %>% 
  mutate(taxonID = as.numeric(taxonID)) %>%
  select(taxonID, commonName) %>% glimpse

origin_lu <-  mdb.get(knights_access_db, "luFishOrigin") %>% 
  select(-activeID) %>% glimpse

debris_volume_lu <- mdb.get(knights_access_db,  "luDebrisVolumeCat") %>% 
  select(-activeID) %>% 
  glimpse

trap_function_lu <- mdb.get(knights_access_db, "luTrapFunctioning") %>%
  select(-activeID) %>% 
  glimpse

processed_lu <- mdb.get(knights_access_db, "luFishProcessed") %>%
  select(-activeID) %>% 
  glimpse

subsite_lu <- mdb.get(knights_access_db, "SubSite") %>% 
  select(subSiteName, subSiteID) %>% 
  filter(subSiteName != "N/A")
```

# Catch
```{r}
detach(package:Hmisc)
# select relevant column
selected_trap_visit <- trap_visit %>%
  select(trapVisitID, visitTime, visitTime2) %>%
  left_join(visit_type_lu, by = c("trapVisitID" = "visitTypeID")) %>%
  glimpse

selected_catch <- catch_raw %>% 
  select(catchRawID, taxonID, finalRunID, finalRunMethodID, fishOriginID, lifeStageID, forkLength, weight, n, trapVisitID, releaseID) %>% 
  left_join(taxon_lu, by = c("taxonID" = "taxonID")) %>%
  filter(commonName == "Chinook salmon") %>% 
  left_join(run_lu, by = c("finalRunID" = "runID")) %>%
  left_join(run_method_lu, by = c("finalRunMethodID" = "runMethodID")) %>%
  left_join(lifestage_lu, by = c("lifeStageID" = "lifeStageID")) %>%
  left_join(origin_lu, by = c("fishOriginID" = "fishOriginID")) %>%
  select(-lifeStageID, -finalRunMethodID, -finalRunID, -taxonID, -fishOriginID) %>%
  left_join(selected_trap_visit) %>%
  # filter out marked and recapture fish by selecting for only fish where release trial does not exist
  filter(releaseID == 0 | releaseID == 255) %>% 
  glimpse

# Save data to google cloud
f <- function(input, output) write_csv(input, file = output)
gcs_upload(selected_catch,
           object_function = f,
           type = "csv",
           name = "rst/lower-sac-river/data-raw/knights-landing/knights_catch_camp.csv",
           predefinedAcl = "bucketLevel")

```

# Trap
```{r}
# all NA
filter(trap_visit, !is.na(timeSampleStarted))
filter(trap_visit, !is.na(timeSampleEnded))
filter(trap_visit, !is.na(inThalwegID))
filter(trap_visit, !is.na(sampleGearID))
filter(trap_visit, !is.na(coneDepthAtStart))
filter(trap_visit, !is.na(coneDepthAtEnd))
filter(trap_visit, !is.na(debrisVolume))

# select relevant variables from trapvisit table
trap_visit_format <- trap_visit %>% 
  select(trapVisitID, trapPositionID, visitTime, visitTime2, visitTypeID, fishProcessedID, trapFunctioningID, counterAtStart, counterAtEnd, rpmRevolutionsAtStart, rpmRevolutionsAtStart, halfConeID, debrisVolumeCatID, comments) %>% 
  left_join(subsite_lu, by = c("trapPositionID" = "subSiteID")) %>% 
  left_join(visit_type_lu) %>% 
  left_join(processed_lu) %>% 
  left_join(trap_function_lu) %>% 
  left_join(debris_volume_lu) %>% 
  mutate(halfCone = ifelse(halfConeID == 1, T, F)) %>% 
  select(-c(trapPositionID, visitTypeID, fishProcessedID, trapFunctioningID, debrisVolumeCatID, halfConeID))

# Save data to google cloud
f <- function(input, output) write_csv(input, file = output)
gcs_upload(trap_visit_format,
           object_function = f,
           type = "csv",
           name = "rst/lower-sac-river/data-raw/knights-landing/knights_trap_camp.csv",
           predefinedAcl = "bucketLevel")
```