---
title: "Tisdale Catch Data Pull"
output: html_document
date: "2022-09-02"
---

This document queries the CAMP database provided by Drew Honeycutt (09/01/2022) to extract
RST catch data for Tisdale trap. Previous files QC'd Excel files provided by
Drew Honeycutt.

*Important to filter releaseID == 0 or releasedID == 255 to exclude recaptures*

```{r}
library(tidyverse)
library(knitr)
library(Hmisc)
library(lubridate)
library(googleCloudStorageR)
root.dir <- rprojroot::find_rstudio_root_file()
knitr::opts_knit$set(root.dir)
```

```{r}
gcs_auth(json_file = Sys.getenv("GCS_AUTH_FILE"))
gcs_global_bucket(bucket = Sys.getenv("GCS_DEFAULT_BUCKET"))
```
# Pull in data tables

```{r}
# TODO
# Set up non-local connection with CAMP access database 
tisdale_access_db <- "/Users/ashleyvizek/code/tisdale_CAMP.mdb"
mdb.get(tisdale_access_db, tables = T)

catch_raw <- mdb.get(tisdale_access_db, tables = "CatchRaw")
trap_visit <- mdb.get(tisdale_access_db, tables = "TrapVisit")
mark <-  mdb.get(tisdale_access_db, tables = "MarkExisting")
# might be able to pull some information from 2016, 2021, 2022
release <- mdb.get(tisdale_access_db, tables = "Release")
# no helpful information in this table
release_fish <- mdb.get(tisdale_access_db, tables = "ReleaseFish")
```
# Lookup tables
```{r}
# pull lookup tables
visit_type_lu <- mdb.get(tisdale_access_db, "luVisitType") %>% 
  select(-activeID) %>%glimpse

run_lu <- mdb.get(tisdale_access_db, "luRun") %>% 
  select(-activeID) %>% glimpse

run_method_lu <- mdb.get(tisdale_access_db, "luRunMethod") %>% 
  select(-activeID) %>% glimpse

lifestage_lu <- mdb.get(tisdale_access_db, "luLifeStage") %>% 
  select(-activeID) %>% glimpse

taxon_lu <-  mdb.get(tisdale_access_db, "luTaxon") %>% 
  mutate(taxonID = as.numeric(taxonID)) %>%
  select(taxonID, commonName) %>% glimpse

origin_lu <-  mdb.get(tisdale_access_db, "luFishOrigin") %>% 
  select(-activeID) %>% glimpse

debris_volume_lu <- mdb.get(tisdale_access_db,  "luDebrisVolumeCat") %>% 
  select(-activeID) %>% 
  glimpse

trap_function_lu <- mdb.get(tisdale_access_db, "luTrapFunctioning") %>%
  select(-activeID) %>% 
  glimpse

processed_lu <- mdb.get(tisdale_access_db, "luFishProcessed") %>%
  select(-activeID) %>% 
  glimpse

subsite_lu <- mdb.get(tisdale_access_db, "SubSite") %>% 
  select(subSiteName, subSiteID) %>% 
  filter(subSiteName != "N/A")

site_lu <- mdb.get(tisdale_access_db, "Site") %>% 
  select(siteName, siteID)

sample_gear_lu <- mdb.get(tisdale_access_db, "luSampleGear") %>% 
  select(-activeID) %>% glimpse()

no_yes_lu <- mdb.get(tisdale_access_db, "luNoYes")

# lookups for existing mark
color_lu <- mdb.get(tisdale_access_db, "luColor") %>%
  select(-activeID) %>% glimpse()

mark_type_lu <- mdb.get(tisdale_access_db, "luMarkType") %>%
  select(-activeID) %>% glimpse()

body_part_lu <- mdb.get(tisdale_access_db, "luBodyPart") %>%
  select(-activeID) %>% glimpse()

# lookups for releases
release_purpose_lu <- mdb.get(tisdale_access_db, "luReleasePurpose") %>% 
   select(-activeID) %>% glimpse()

light_condition_lu <- mdb.get(tisdale_access_db, "luLightCondition") %>% 
   select(-activeID) %>% glimpse()
```

# Catch (not including recaptures)

```{r}
detach(package:Hmisc)
# select relevant column
selected_trap_visit <- trap_visit %>%
  select(trapVisitID, visitTime, visitTime2, visitTypeID) %>%
  left_join(visit_type_lu, by = c("visitTypeID" = "visitTypeID")) %>% 
  select(-visitTypeID)

selected_mark_existing <- mark %>% 
  select(catchRawID, markTypeID, markColorID, markPositionID) %>% 
  left_join(mark_type_lu, by = c("markTypeID" = "markTypeID")) %>% 
  left_join(color_lu, by = c("markColorID" = "colorID")) %>% 
  left_join(body_part_lu, by = c("markPositionID" = "bodyPartID")) %>% 
  select(-c(markTypeID, markColorID, markPositionID))

selected_catch <- catch_raw %>% 
  select(catchRawID, taxonID, finalRunID, finalRunMethodID, fishOriginID, lifeStageID, forkLength, weight, n, trapVisitID, releaseID, mortID) %>% 
  left_join(taxon_lu, by = c("taxonID" = "taxonID")) %>%
  # filter(commonName == "Chinook salmon") %>% 
  left_join(run_lu, by = c("finalRunID" = "runID")) %>%
  left_join(run_method_lu, by = c("finalRunMethodID" = "runMethodID")) %>%
  left_join(lifestage_lu %>% 
              select(-lifeStageCAMPID), by = c("lifeStageID" = "lifeStageID")) %>%
  left_join(origin_lu, by = c("fishOriginID" = "fishOriginID")) %>%
  left_join(no_yes_lu, by = c("mortID" = "noYesID")) %>% 
  rename(dead = noYes) %>% 
  select(-lifeStageID, -finalRunMethodID, -finalRunID, -taxonID, -fishOriginID, - mortID) %>%
  # add existing mark data
  left_join(selected_mark_existing, by = c("catchRawID" = "catchRawID")) %>% 
  left_join(selected_trap_visit) %>%
  # filter out marked and recapture fish by selecting for only fish where release trial does not exist
  filter(releaseID == 0 | releaseID == 255) %>% 
  glimpse

# Save data to google cloud
f <- function(input, output) write_csv(input, file = output)
gcs_upload(selected_catch,
           object_function = f,
           type = "csv",
           name = "rst/lower-sac-river/data-raw/tisdale/tisdale_catch_camp.csv",
           predefinedAcl = "bucketLevel")

```
# Recaptures

```{r}
trap_visit_recaptures <- trap_visit %>%
  select(trapVisitID, visitTime, visitTime2, visitTypeID, halfConeID) %>%
  left_join(visit_type_lu, by = c("visitTypeID" = "visitTypeID")) %>% 
  mutate(halfCone = ifelse(halfConeID == 1, T, F)) %>% 
  select(-visitTypeID, -halfConeID)

selected_recaptured <- catch_raw %>% 
  select(catchRawID, taxonID, finalRunID, finalRunMethodID, fishOriginID, lifeStageID, forkLength, weight, n, trapVisitID, releaseID, mortID) %>% 
  left_join(taxon_lu, by = c("taxonID" = "taxonID")) %>%
  # filter(commonName == "Chinook salmon") %>% 
  left_join(run_lu, by = c("finalRunID" = "runID")) %>%
  left_join(run_method_lu, by = c("finalRunMethodID" = "runMethodID")) %>%
  left_join(lifestage_lu %>% 
              select(-lifeStageCAMPID), by = c("lifeStageID" = "lifeStageID")) %>%
  left_join(origin_lu, by = c("fishOriginID" = "fishOriginID")) %>%
  left_join(no_yes_lu, by = c("mortID" = "noYesID")) %>% 
  rename(dead = noYes) %>% 
  select(-lifeStageID, -finalRunMethodID, -finalRunID, -taxonID, -fishOriginID, - mortID) %>%
  left_join(trap_visit_recaptures) %>%
  # filter out marked and recapture fish by selecting for only fish where release trial does not exist
  filter(releaseID != 0 & releaseID != 255) %>% 
  glimpse

f <- function(input, output) write_csv(input, file = output)
gcs_upload(selected_recaptured,
           object_function = f,
           type = "csv",
           name = "rst/lower-sac-river/data-raw/tisdale/tisdale_recaptures_camp.csv",
           predefinedAcl = "bucketLevel")
```
# Releases

```{r}
# removed releasepurposeID because they are all trap efficiency tests
selected_release <- release %>% 
  filter(releaseID != 255 & releaseID  != 0) %>% 
  select(releaseID, markedTaxonID, markedRunID, markedFishOriginID, sourceOfFishSiteID, releaseSiteID, releaseSubSiteID, nMortWhileHandling, nMortAtCheck, nReleased, releaseTime, releaseLightConditionID, testDays) %>% 
  left_join(taxon_lu, by = c("markedTaxonID" = "taxonID")) %>%
  # filter(commonName == "Chinook salmon") %>% 
  left_join(run_lu, by = c("markedRunID" = "runID")) %>%
  left_join(origin_lu, by = c("markedFishOriginID" = "fishOriginID")) %>%
  left_join(site_lu, by = c("sourceOfFishSiteID" = "siteID")) %>% 
  rename(site_fish_source = siteName) %>% 
  left_join(site_lu, by = c("releaseSiteID" = "siteID")) %>% 
  rename(release_site = siteName) %>% 
  left_join(subsite_lu, by = c("releaseSubSiteID" = "subSiteID")) %>% 
  left_join(light_condition_lu, by = c("releaseLightConditionID" = "lightConditionID")) %>% 
  select(-c(markedTaxonID, markedRunID, markedFishOriginID, sourceOfFishSiteID, releaseSiteID, releaseSubSiteID, releaseLightConditionID))
  
f <- function(input, output) write_csv(input, file = output)
gcs_upload(selected_release,
           object_function = f,
           type = "csv",
           name = "rst/lower-sac-river/data-raw/tisdale/tisdale_releases_camp.csv",
           predefinedAcl = "bucketLevel")
```

# Trap
```{r}
# all NA
filter(trap_visit, !is.na(timeSampleStarted))
filter(trap_visit, !is.na(timeSampleEnded))
filter(trap_visit, !is.na(coneDepthAtStart))
filter(trap_visit, !is.na(coneDepthAtEnd))
filter(trap_visit, !is.na(debrisVolume))

# not NA
filter(trap_visit, !is.na(inThalwegID))
filter(trap_visit, !is.na(sampleGearID))

# select relevant variables from trapvisit table
trap_visit_format <- trap_visit %>% 
  select(trapVisitID, trapPositionID, visitTime, visitTime2, visitTypeID, fishProcessedID, sampleGearID, inThalwegID, trapFunctioningID, counterAtStart, counterAtEnd, rpmRevolutionsAtStart, rpmRevolutionsAtEnd, halfConeID, debrisVolumeCatID, comments) %>% 
  left_join(subsite_lu, by = c("trapPositionID" = "subSiteID")) %>% 
  left_join(visit_type_lu) %>% 
  left_join(processed_lu) %>% 
  left_join(sample_gear_lu) %>% 
  left_join(no_yes_lu, by = c("inThalwegID" = "noYesID")) %>% 
  rename(inThalweg = noYes) %>% 
  left_join(trap_function_lu) %>% 
  left_join(debris_volume_lu) %>% 
  mutate(halfCone = ifelse(halfConeID == 1, T, F)) %>% 
  select(-c(trapPositionID, visitTypeID, fishProcessedID, sampleGearID, inThalwegID, trapFunctioningID, debrisVolumeCatID, halfConeID))

# Save data to google cloud
f <- function(input, output) write_csv(input, file = output)
gcs_upload(trap_visit_format,
           object_function = f,
           type = "csv",
           name = "rst/lower-sac-river/data-raw/tisdale/tisdale_trap_camp.csv",
           predefinedAcl = "bucketLevel")
```