---
title: "butte-creek-rst-qc-checklist"
author: "Inigo Peng"
date: "10/19/2021"
output: rmarkdown::github_document
---
```{r}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
library(tidyverse)
library(lubridate)
library(googleCloudStorageR)
library(ggplot2)
library(scales)
library (RColorBrewer)
```
# Butte Creek RST Data  

## Description of Monitoring Data

**Timeframe:** 


**Completeness of Record throughout timeframe:**  

**Sampling Location:** 


**Data Contact:** [Jessica Nichols](mailto:Jessica.Nichols@Wildlife.ca.gov)


## Access Cloud Data

```{r, eval=FALSE}
# Run Sys.setenv() to specify GCS_AUTH_FILE and GCS_DEFAULT_BUCKET before running
# Open object from google cloud storage
# Set your authentication using gcs_auth
gcs_auth(json_file = Sys.getenv("GCS_AUTH_FILE"))
# Set global bucket 
gcs_global_bucket(bucket = Sys.getenv("GCS_DEFAULT_BUCKET"))
gcs_list_objects()
# git data and save as xlsx
gcs_get_object(object_name = "rst/butte-creek/data-raw/CDFW_Butte_Creek_RST_Captures.xlsx",
               bucket = gcs_get_global_bucket(),
               saveToDisk = "butte_creek_rst_raw.xlsx",
               Overwrite = TRUE)
```
```{r}
raw_data = readxl::read_excel('butte_creek_rst_raw.xlsx')
glimpse(raw_data)
```

