---
title: "Explore Variables"
author: "Erin Cain"
date: "12/14/2021"
output: rmarkdown::github_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(wordcloud2)
```

## Adult Upstream Passage 


```{r}
# VIDEO DATA 
# Battle Creek 
battle_video <- readRDS("../../data/battle_adult_video_passage_data_dictionary.rds") %>% 
  mutate(location = "Battle Creek") %>% glimpse

# Clear Creek 
clear_video <- readRDS("../../data/clear_adult_passage_data_dictionary.rds")%>% 
  mutate(location = "Clear Creek") %>% glimpse

# Deer Creek 
deer_video <- readRDS("../../data/deer_adult_passage_data_dictionary.rds")%>% 
  mutate(location = "Deer Creek") %>% glimpse

# Yuba River 
yuba_video <- readRDS("../../data/yuba_adult_passage_data_dictionary.rds") %>% 
  mutate(location = "Yuba River") %>% glimpse

adult_upstream_video_variables <- 
  bind_rows(battle_video, clear_video, deer_video, yuba_video) %>% 
  group_by(variables) %>%
  tally() %>%
  glimpse()

# View(adult_upstream_video_variables)
```
```{r}
set.seed(2)
wordcloud2(adult_upstream_video_variables)
```


```{r}
# Passage Estimates 
# Battle Creek 
battle_passage_estimates <- readRDS("../../data/battle_adult_passage_estimates_data_dictionary.rds") %>% 
  mutate(location = "Battle Creek") %>% glimpse

# Deer Creek 
deer_passage_estimates <- readRDS("../../data/deer_adult_passage_data_dictionary.rds")%>% 
  mutate(location = "Deer Creek") %>% glimpse

# Mill Creek
mill_passage_estimates <- readRDS("../../data/mill_adult_passage_data_dictionary.rds") %>% 
  mutate(location = "Mill Creek") %>% glimpse

adult_upstream_passage_estimate_variables <- 
  bind_rows(battle_passage_estimates, deer_passage_estimates, mill_passage_estimates) %>% 
  group_by(variables) %>%
  tally() %>%
  glimpse()

# View(adult_upstream_passage_estimate_variables)
```
```{r}
set.seed(2)
wordcloud2(adult_upstream_passage_estimate_variables, size = .75)
```

```{r}


battle_trap <- readRDS("../../data/battle_adult_trap_data_dictionary.rds") %>% 
  mutate(location = "Battle Creek") %>% glimpse
```


## Carcass Surveys 

```{r}
battle_carcass <- readRDS("../../data/battle_carcass_data_dictionary.rds") %>% 
  mutate(location = "Battle Creek") %>% glimpse

butte_carcass <- readRDS("../../data/butte_carcass_individuals_2_data_dictionary.rds") %>% 
  mutate(location = "Butte Creek") %>% glimpse

clear_carcass <- readRDS("../../data/clear_carcass_data_dictionary.rds") %>% 
  mutate(location = "Clear Creek") %>% glimpse

carcass_survey_variables <- bind_rows(battle_carcass, butte_carcass, clear_carcass) %>%
  group_by(variables) %>% 
  tally()

# Seems to be more simplified, TODO better understand difference between CHOPS and Survey Individuals
butte_chops <- readRDS("../../data/butte_carcass_chops_data_dictionary.rds") %>% 
  mutate(location = "Butte Creek") %>% glimpse

View(carcass_survey_variables)
```

```{r}
set.seed(3746)
wordcloud2(carcass_survey_variables, size = .45)
```

## Redd Survey 

```{r}
battle_redd <- readRDS("data/battle_redd_data_dictionary.rds") %>% 
  mutate(location = "Battle Creek") %>% glimpse

clear_redd <- readRDS("data/clear_redd_data_dictionary.rds") %>% 
  mutate(location = "Clear Creek") %>% glimpse

feather_redd <- readRDS("data/feather_redd_data_dictionary.rds") %>% 
  mutate(location = "Feather River") %>% glimpse

mill_redd <- readRDS("data/mill_redd_data_dictionary.rds") %>% 
  mutate(location = "Mill Creek") %>% glimpse

redd_full <- bind_rows(battle_redd, clear_redd, feather_redd, mill_redd)

redd_survey_variables <- redd_full %>%
  group_by(variables) %>% 
  tally() %>% 
  glimpse()

View(redd_survey_variables)

# Condensing variables that are the same #######################################
# Determining which descriptions to keep
redd_survey_variable_descriptions <- redd_full %>%
  mutate(keep = case_when(variables %in% c("comments", "latitude", "longitude") ~ "Battle Creek",
                          variables %in% c("location", "redd_count") ~ "Mill Creek",
                          variables %in%  c("date", "pre_redd_depth", "pre_redd_substrate_size",
                                            "redd_pit_depth", "redd_substrate_size",
                                            "redd_tail_depth", "tail_substrate_size") ~ "Clear Creek",
                          T ~ location)) %>%
  filter(location == keep) %>%
  select(-c(location, keep, percent_na)) 

# correcting variable names that are the same 
redd_survey_variables_names <- redd_survey_variables %>%
  mutate(standard_name = case_when(
                                   #variables == "date_measured" ~ "date",
                                   variables == "fish_on_redd" ~ "fish_guarding",
                                   variables %in% c("redd_length_in", "redd_length_m") ~ "redd_length",
                                   variables %in% c("redd_width_in", "redd_width_m") ~ "redd_width",
                                   variables == "surveyed_reach" ~ "reach",
                                   variables == "measured" ~ "redd_measured",
                                   T ~ variables)) %>%
  distinct(standard_name)

redd_full_data_dictionary <- left_join(redd_survey_variables_names %>%
                                         rename(variables = standard_name), 
                                       redd_survey_variable_descriptions) %>%
  distinct(variables, .keep_all= T)
write_csv(redd_full_data_dictionary, file = "scripts/synthesis/redd_full_data_dictionary.csv")
```

```{r}
set.seed(3746)
wordcloud2(redd_survey_variables, size = .45)
```

## Holding Survey

```{r}
battle_holding <- readRDS("../../data/battle_holding_data_dictionary.rds") %>% 
  mutate(location = "Battle Creek") %>% glimpse

clear_holding <- readRDS("../../data/clear_holding_data_dictionary.rds") %>% 
  mutate(location = "Clear Creek") %>% glimpse

deer_holding <- readRDS("../../data/deer_holding_data_dictionary.rds") %>% 
  mutate(location = "Deer River") %>% glimpse

holding_survey_variables <- bind_rows(battle_holding, clear_holding, deer_holding) %>%
  group_by(variables) %>% 
  tally() %>% 
  glimpse()
```

```{r}
set.seed(3746)
wordcloud2(holding_survey_variables, size = .45)
```


## RST Variables

```{r}
battle_rst <- readRDS("../../data/battle_rst_data_dictionary.rds") %>%
  mutate(location = "Battle Creek") %>% glimpse

butte_rst <- readRDS("../../data/butte_rst_data_dictionary.rds") %>% 
  mutate(location = "Butte Creek") %>% glimpse

clear_rst <- readRDS("../../data/clear_rst_data_dictionary.rds") %>% 
  mutate(location = "Clear Creek") %>% glimpse

deer_rst <- readRDS("../../data/deer_rst_data_dictionary.rds") %>% 
  mutate(location = "Deer Creek") %>% glimpse

#TODO feather river RST
feather_rst <- readRDS("../../data/feather_rst_data_dictionary.rds") %>% 
  mutate(location = "Feather River") %>% glimpse()

mill_rst <- readRDS("../../data/mill_rst_data_dictionary.rds") %>% 
  mutate(location = "Mill Creek") %>% glimpse

yuba_rst <- readRDS("../../data/yuba_rst_data_dictionary.rds") %>% 
  mutate(location = "Yuba River") %>% glimpse

knights_rst <- readRDS("../../data/lower_sac_knights_rst_data_dictionary.rds") %>% 
  mutate(location = "Sac River - Knights") %>% glimpse

tisdale_rst <- readRDS("../../data/lower_sac_tisdale_rst_data_dictionary.rds") %>% 
  mutate(location = "Sac River - Tisdale") %>% glimpse


rst_catch_variables <- bind_rows(battle_rst, butte_rst, clear_rst, deer_rst, feather_rst, mill_rst, yuba_rst, knights_rst, tisdale_rst) %>%
  group_by(variables) %>% 
  tally() %>% 
  glimpse()

View(rst_catch_variables)
```

```{r}
set.seed(3746)
wordcloud2(rst_catch_variables, size = .6)
```



##### RST effort & efficency
```{r}
battle_rst_operations <- readRDS("../../data/battle_rst_environmental_data_dictionary.rds") %>%
  mutate(location = "Battle Creek") %>% glimpse

# Butte all in one table 

clear_rst_operations <- readRDS("../../data/clear_rst_environmental_data_dictionary.rds") %>% 
  mutate(location = "Clear Creek") %>% glimpse

# Deer all in one table 

feather_rst_operations <- readRDS("../../data/feather_rst_effort_data_dictionary.rds") %>% 
  mutate(location = "Feather River") %>% glimpse()

# Mill all in one table

# Yuba all in one table 

knights_rst_operations <- readRDS("../../data/lower_sac_knights_rst_effort_data_dictionary.rds") %>% 
  mutate(location = "Sac River - Knights") %>% glimpse

# Tisdale all in one table 

rst_operations_variables <- bind_rows(battle_rst_operations, clear_rst_operations, knights_rst_operations) %>%
  group_by(variables) %>% 
  tally() %>% 
  glimpse()

View(rst_operations_variables)
```
```{r}
set.seed(3746)
wordcloud2(rst_operations_variables, size = .25)

```






