---
title: "combine flow data for trap locations"
output: 
  html_document:
  theme: flatly
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, fig.width=15, fig.height=10)

Sys.setenv("GCS_AUTH_FILE" = "config.json")
Sys.setenv("GCS_DEFAULT_BUCKET" = "jpe-dev-bucket")

library(tidyverse)
library(googleCloudStorageR)
```

# Pull in data and format {.tabset}

## Battle

```{r}
# Pull in flow data saved in flow_data_prep.Rmd
# Format data as date, flow_cfs, stream, site, source

# source USGS
battle <- read_rds(here::here("data-raw", "standard-format-data-prep", "flow_data_prep_files", "flow_data", "battle_flow.rds"))

battle_format <- battle %>%
  mutate(site = "ubc") %>%
  mutate(stream = "battle creek",
         source = "USGS 11376550") %>%
  glimpse()
```

## Butte

```{r}
# source CDEC
butte <- read_rds(here::here("data-raw", "standard-format-data-prep", "flow_data_prep_files", "flow_data", "butte_flow.rds"))

butte_format <- butte %>%
  mutate(site = "adams dam") %>%
  bind_rows(butte %>%
              mutate(site = "okie dam")) %>%
  mutate(stream = "butte creek",
         source = "CDEC BCK") %>%
glimpse()
```

## Clear

```{r}
# source USGS
clear <- read_rds(here::here("data-raw", "standard-format-data-prep", "flow_data_prep_files", "flow_data", "clear_flow.rds"))

clear_format <- clear %>%
  mutate(site = "ucc") %>%
  bind_rows(clear %>%
            mutate(site = "lcc")) %>%
  mutate(stream = "clear creek",
         source = "USGS 11372000") %>%
glimpse()
```

## Deer

```{r}
# source USGS
deer <- read_rds(here::here("data-raw", "standard-format-data-prep", "flow_data_prep_files", "flow_data", "deer_flow.rds"))

deer_format <- deer %>%
  mutate(stream = "deer creek",
         site = stream,
         source = "USGS 11383500") %>%
glimpse()
```

## Feather
### Feather High flow channel

```{r}
# source CDEC
feather_hfc <- read_rds(here::here("data-raw", "standard-format-data-prep", "flow_data_prep_files", 
                                   "flow_data", "feather_hfc_flow.rds"))
# Add in all feather sites
# hfc_sites <- c("herringer riffle", "live oak", "shawn's beach", "sunset pumps")
feather_herringer <- feather_hfc %>%
  mutate(stream = "feather river",
         source = "CDEC GRL",
         site = "herringer riffle") %>%
  glimpse()

feather_live_oak <- feather_hfc %>%
  mutate(stream = "feather river",
         source = "CDEC GRL",
         site = "live oak") %>%
  glimpse()

feather_shawns_beach <- feather_hfc %>%
  mutate(stream = "feather river",
         source = "CDEC GRL",
         site = "shawn's beach") %>%
  glimpse()

feather_sunset_pumps <- feather_hfc %>%
  mutate(stream = "feather river",
         source = "CDEC GRL",
         site = "sunset pumps") %>%
  glimpse()

feather_hfc_format <- bind_rows(feather_herringer, feather_live_oak, feather_shawns_beach, feather_sunset_pumps)
```

### Feather Low flow channel

```{R}

# source USGS
feather_lfc <- read_rds(here::here("data-raw", "standard-format-data-prep", "flow_data_prep_files", 
                                   "flow_data", "feather_lfc_flow.rds"))
# Add in all feather sites
# lfc_sites <- c("eye riffle", "gateway riffle", "steep riffle")
feather_eye_riffle <- feather_lfc %>%
  mutate(stream = "feather river",
         source = "USGS 11407000",
         site = "eye riffle") %>%
  glimpse()

feather_gateway_riffle <- feather_lfc %>%
  mutate(stream = "feather river",
         source = "USGS 11407000",
         site = "gateway riffle") %>%
  glimpse()

feather_steep_riffle <- feather_lfc %>%
  mutate(stream = "feather river",
         source = "USGS 11407000",
         site = "steep riffle") %>%
  glimpse()

feather_lfc_format <- bind_rows(feather_eye_riffle, feather_gateway_riffle, feather_steep_riffle)



```
### Lower Feather 
```{r}

#CDEC
# source lower feather
lower_feather <- read_rds(here::here("data-raw", "standard-format-data-prep", 
                                     "flow_data_prep_files", "flow_data",
                                     "lower_feather_flow.rds"))
lower_feather_format <- lower_feather |> 
  mutate(stream = "feather river",
         source = "CDEC FBS", 
         site = "lower feather") |> 
  glimpse()


```

## Mill

```{r}
# source USGS
mill <- read_rds(here::here("data-raw", "standard-format-data-prep", "flow_data_prep_files", "flow_data", "mill_flow.rds"))

mill_format <- mill %>%
  mutate(stream = "mill creek",
         site = stream, 
         source = "USGS 11381500") %>%
glimpse()
```

## Yuba

```{r}
# source USGS
yuba <- read_rds(here::here("data-raw", "standard-format-data-prep", "flow_data_prep_files", "flow_data", "yuba_flow.rds"))

yuba_format <- yuba %>%
  mutate(site = "yuba river") %>%
  bind_rows(yuba %>%
              mutate(site = "hallwood")) %>%
  mutate(stream = "yuba river",
         source = "USGS 11421000") %>%
glimpse()
```

## Sacramento

```{r}
# source USGS
knights <- read_rds(here::here("data-raw", "standard-format-data-prep", "flow_data_prep_files", "flow_data", "knights_flow.rds"))

knights_format <- knights %>%
  mutate(stream = "sacramento river",
         site = "knights landing",
         source = "USGS 11390500") %>%
glimpse()

# source USGS (same as Knights)
tisdale <- read_rds(here::here("data-raw", "standard-format-data-prep", "flow_data_prep_files", "flow_data", "tisdale_flow.rds"))

tisdale_format <- tisdale %>%
  mutate(stream = "sacramento river",
         site = "tisdale",
         source = "USGS 11390500") %>%
glimpse()

# source USGS (red bluff)

red_bluff <- read_rds(here::here("data-raw", "standard-format-data-prep", "flow_data_prep_files", "flow_data", "rb_flow.rds"))

red_bluff_format <- red_bluff |> 
   mutate(stream = "sacramento river",
         site = "red bluff diversion dam",
         source = "USGS 11377100") %>%
glimpse()
```

# Combine flow data {.tabset}

```{r}
combined_flow <- bind_rows(battle_format,
                           butte_format,
                           clear_format,
                           deer_format,
                           feather_hfc_format,
                           feather_lfc_format,
                           lower_feather_format,
                           mill_format,
                           yuba_format,
                           knights_format,
                           tisdale_format,
                           red_bluff_format) %>%
  glimpse()
```
## QA/QC

```{r}
unique(combined_flow$stream)
unique(combined_flow$site)

ggplot(combined_flow, aes(x = date, y = flow_cfs, color = stream)) +
  geom_line()

filter(combined_flow, is.na(date))

combined_flow_clean <- filter(combined_flow, !is.na(date))
```

```{r}
f <- function(input, output) write_csv(input, file = output)

gcs_auth(json_file = Sys.getenv("GCS_AUTH_FILE"))
gcs_global_bucket(bucket = Sys.getenv("GCS_DEFAULT_BUCKET"))

gcs_upload(combined_flow_clean,
           object_function = f,
           type = "csv",
           name = "standard-format-data/standard_flow.csv",
           predefinedAcl = "bucketLevel")

write_csv(combined_flow_clean, here::here("data", "standard-format-data", "standard_flow.csv"))
```