---
title: "First catch and efficiency/flow analyses"
author: "Ashley Vizek"
date: "6/22/2022"
output:
  html_document:
     code_folding: hide
     theme: flatly
---

Quick analyses in preparation for the RST efficiency workshop.

```{r setup, include = T}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, fig.width=15, fig.height=10)
library(leaflet)
library(scales)
library(tidyverse)
library(googleCloudStorageR)
library(lubridate)
knitr::opts_knit$set(root.dir = '/JPE-datasets')
colors_small <-  c("#9A8822", "#F5CDB4", "#F8AFA8", "#FDDDA0", "#74A089", #Royal 2
                   "#899DA4", "#C93312", "#DC863B" # royal 1 (- 3)
)

colors_full <-  c("#9A8822", "#F5CDB4", "#F8AFA8", "#FDDDA0", "#74A089", #Royal 2
                  "#899DA4", "#C93312", "#DC863B", # royal 1 (- 3)
                  "#F1BB7B", "#FD6467", "#5B1A18", # Grand Budapest 1 (-4)
                  "#D8B70A", "#02401B", "#A2A475", # Cavalcanti 1
                  "#E6A0C4", "#C6CDF7", "#D8A499", "#7294D4", #Grand Budapest 2
                  "#9986A5", "#EAD3BF", "#AA9486", "#B6854D", "#798E87" # Isle of dogs 2 altered slightly
)

gcs_get_object(object_name = "standard-format-data/standard_rst_catch.csv",
                 bucket = gcs_get_global_bucket(),
                 saveToDisk = "standard_rst_catch.csv",
                 overwrite = TRUE)

gcs_get_object(object_name = "standard-format-data/standard_flow.csv",
                 bucket = gcs_get_global_bucket(),
                 saveToDisk = here::here("data", "standard-format-data", "standard_flow.csv"),
                 overwrite = TRUE)

gcs_get_object(object_name = "standard-format-data/standard_recapture.csv",
                 bucket = gcs_get_global_bucket(),
                 saveToDisk = here::here("data", "standard-format-data", "standard_recapture.csv"),
                 overwrite = TRUE)

gcs_get_object(object_name = "standard-format-data/standard_release.csv",
                 bucket = gcs_get_global_bucket(),
                 saveToDisk = here::here("data", "standard-format-data", "standard_release.csv"),
                 overwrite = TRUE)
```

```{r}
catch_raw <- read_csv(here::here("data","standard-format-data", "standard_rst_catch.csv"))
flow_raw <- read_csv(here::here("data","standard-format-data", "standard_flow.csv"))
recapture_raw <- read_csv(here::here("data","standard-format-data", "standard_recapture.csv"))
release_raw <- read_csv(here::here("data","standard-format-data", "standard_release.csv"))
```

## Flow and trap efficiency

There is a slight inverse relationship between flow and efficiency. Trap efficiency
is generally higher at lower flows. There is not much of a trend for the Sacramento
likely because we do not have enough data points and all efficiencies are less than
0.02.

```{r}
number_released_flow <- release_raw %>% 
  select(stream, site, release_id, release_date, number_released, flow_at_release)

number_recaptured <- recapture_raw %>% 
  mutate(number_recaptured = ifelse(is.na(number_recaptured), 0, number_recaptured)) %>% 
  group_by(stream, release_id) %>% 
  summarize(number_recaptured = sum(number_recaptured))

efficiency <- left_join(number_released_flow, number_recaptured) %>% 
  mutate(efficiency = number_recaptured/number_released) %>% 
  left_join(flow_raw %>% 
              select(date, flow_cfs, stream, site) %>% 
              rename(release_date = date)) %>% 
  mutate(flow_at_release = ifelse(is.na(flow_at_release), flow_cfs, flow_at_release))

ggplot(filter(efficiency, efficiency < 0.4), aes(x = efficiency, y = log(flow_at_release))) +
  geom_point() +
  facet_wrap(~stream, scales = "free_x")
```

